### ISSUE TITLE
Algorithm job OOMKilled will forever deserted and block further new job from the same wallet

### ISSUE THREAD

**Issue by soonhuat** [oceanprotocol/operator-engine#78]
**Describe the bug**
As an algorithm jobs OOMKilled because allocated memory were not enough for the whole process, the algorithm job will be deserted in the namespace.
Associated configmap and other kubernetes objects also not removed. 
Database table jobs, column status will forever stays as 40: Running algorithm
Thus, when operator-engine trigger db function announce_and_get_sql_pending_jobs, will always return the OOMKilled algorithm job, and no new job from this wallet can be started.

**To Reproduce**
1. Setup operator-engine with with env var configure to be nCPU: 1 and ramGB: 1
2. Publish algorithm and dataset that will run more than 10min and progressively use extra memory
3. Order and start the compute job

**Expected behavior**
Jobs pod killed gracefully and next subsequent job will able to be run.

**Screenshots**
`Running pod`
<img width="651" alt="image" src="https://user-images.githubusercontent.com/7642607/227884805-bfe4d6ae-56fd-4453-808d-b4c911cda901.png">

`Configmap`
<img width="385" alt="image" src="https://user-images.githubusercontent.com/7642607/227885659-29ddcb02-1151-4c4a-a574-5d466ddb99c2.png">

`Database jobs`
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/7642607/227886547-95dc6a4b-bcc0-456a-8821-f177446dd16e.png">

**Comment by LoznianuAnamaria** [comment]
Sorry for the late reply. This is on our radar and we will do it with C2D V2(Upgrades, fixes and refactor)
