### ISSUE TITLE
Operator Engine fails to start if env var maxJobs is set

### ISSUE THREAD

**Issue by rogargon** [oceanprotocol/operator-engine#83]
operator-engine fails to start if the environment variable `maxJobs` is set. 

If it is not set, the default is integer value `10` and the following line works:
https://github.com/oceanprotocol/operator-engine/blob/b530521a306ee66530d534aa0978e2eba64cfcd8/operator_engine/operator_main.py#L228

However, if it is set to any value, for instance, `1`, the value is not converted to an integer and the previous line fails with the following message:

```
max_jobs_to_take = OperatorConfig.ENVIROMENT_maxJobs - current_jobs
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

**Comment by LoznianuAnamaria** [comment]
Thanks for raising this, will look over it in the following days 🙏
